### ISSUE TITLE
 build_rnn function and build_nn function miss  some parameters  in TV Script Generation

### ISSUE THREAD

**Issue by menxia** [udacity/deep-learning#140]
function build_rnn(cell, inputs) also need  initial_state as a parameter for the tf.nn.dynamic_rnn. Otherwise we cannot feed the state to the network.
> def build_rnn(cell, inputs, initial_state):
          outputs, state = tf.nn.dynamic_rnn(cell, inputs, initial_state = initial_state)

build_nn() miss a parameter, batch_size

> def build_nn(cell, rnn_size, input_data, vocab_size, embed_dim, batch_size):
          cell, initial_state = get_init_cell(batch_size, rnn_size)

**Comment by johnsonice** [comment]
totally agree. tried add initial_state myself. it turns our we need to change a lot code to make it work. 

tf.nn.dynamic_run only take initial_state as tuple. if we follow the project requirement and made initial_stated a named tensor, it will throw an error. Some thing for finial_state. 

And also we need to change the way we load the model back, since we don't have those named tensor any more. 

hope this can be fixed soon.

**Comment by rahul-ahuja** [comment]
see this student's answer https://discussions.udacity.com/t/we-created-an-initial-state-in-get-init-cell-but-i-didnt-see-its-passed-into-the-rnn/250443/16

**Comment by ccchang0111** [comment]
In the June class, the build_nn function is modified to **build(cell, rnn_size, input_data, vocab_size, embed_dim)** which now has **'embed_dim'**. However, it seems like **rnn_size** is not being used in this function anymore. Why do we still need this variable as input as we are now using embed_dim in the function? Maybe we can remove rnn_size. Thanks!

**Comment by abhiojha8** [comment]
Yes, rnn_size is redundant.
