### ISSUE TITLE
Request- requirements.txt

### ISSUE THREAD

**Issue by adriantorrie** [udacity/deep-learning#46]
Would be nice to have, so when running the notebooks I don't have to install as a go through cells individually.

**Comment by NeverDoubtTheWorm** [comment]
or even environment.yml s to just import all the relevant dependencies into a conda environment

**Comment by adriantorrie** [comment]
@NeverDoubtTheWorm  agreed

Requesting:
- requirements.txt
- environment.yml

**Comment by Brok-Bucholtz** [comment]
We currently only support our AMI on AWS.  That's because there's a lot of content that needs to be created for all students to be able to setup the environment on their computer.

If you create a pull request and call the file "unofficial_requirements.txt", I'll pull it in.  There's no reason for a Conda environment file, since everything can be installed through pip.

**Comment by Brok-Bucholtz** [comment]
Requierments files have been added.
