### ISSUE TITLE
error in transfer learning solution

### ISSUE THREAD

**Issue by alain2208** [udacity/deep-learning#56]
Hi i tried the solution for transfer learning    

 codes = codes.reshape((len(labels), -1)) 
got the error 

i got this i reduced the number of images as a poc on my PC.

running windows and 3.5.2 python cpu no gpus.

i added print (len(codes )) to verify info.

<ipython-input-20-bdda1202e541> in <module>()
     10     codes = np.fromfile(f, dtype=np.float32)
     11     print(len(codes))
---> 12     codes = codes.reshape((len(labels),-1))

ValueError: cannot reshape array of size 9187328 into shape (2244,newaxis)

**Comment by navyg8r** [comment]
Hi alain, I had a similar issue. In my case, the original code below...
```
    labels = np.array([each for each in reader]).squeeze()
```
...resulted in the last label being in empty label:
```
labels[-1]
>>> []  #the last label should either be 'daisy', 'dandelion', 'roses', 'sunflowers', or 'tulips'
```

The result was like yours in that the array of `codes` could not be reshaped evenly by the length of `labels` because of the erroneous addition of the last label that was empty.

So i added a conditional ` if len(each) > 0` to the original list comprehension to only read in the line if it was not empty:
```
    labels = np.array([each for each in reader if len(each) > 0]).squeeze()
```

This prevented any empty lines from being read in to `labels`; result was the the length of `codes` was now evenly divisible by length of `labels` and the reshape was successful.

Below is the block of code that appears works in my case in the "Building the Classifier" section:
```
# read codes and labels from file
import csv

with open('labels') as f:
    reader = csv.reader(f, delimiter='\n')
    labels = np.array([each for each in reader if len(each) > 0]).squeeze()

with open('codes') as f:
    codes = np.fromfile(f, dtype=np.float32)
    codes = codes.reshape((len(labels), -1))
```

**Comment by alain2208** [comment]
thanks navyg8r worked for me in my case

**Comment by erip** [comment]
@navyg8r Would you submit a PR? That would be good to share in the notebook.

**Comment by navyg8r** [comment]
thanks erip. i'm still a noob at this git so I don't know what PR means (PR=pull request?). i'm still learning git so i'm not yet comfortable with how to do it without breaking something (i almost lost my project 3 work after issuing some git command); since it looks like mat's been assigned this issue, i will wait for mat to fix. i'll research how to do a PR in the meantime.

**Comment by alain2208** [comment]
I'm at the same level as Navyg8r  concerning the usage of Git.

**Comment by mcleonard** [comment]
Hi all, I'm on it!

**Comment by mcleonard** [comment]
Fixed: https://github.com/udacity/deep-learning/commit/8730e18ab1b8aedb3ea5715bd31c53d9d7cd01e7
