### ISSUE TITLE
Add information on how to apply Sentiment Prediction RNN to the notebook

### ISSUE THREAD

**Issue by TheRusskiy** [udacity/deep-learning#70]
How do you apply model built in “Sentiment Prediction RNN” lesson to get sentiment out of some example review you write yourself? So you can later use it in production.

**Comment by mcleonard** [comment]
Thanks for creating this issue. I'll get on it ASAP

**Comment by TheRusskiy** [comment]
@mcleonard sorry to pressure, but any progress?

**Comment by mkowoods** [comment]
@TheRusskiy if you're interested i wrote a version of that code in the below workbook. I was also interested in seeing how the sentiment changes as the sentence progresses. It's a rough hack. I used the same method as the lesson so it zero pads/truncates the inputs to be size 200, but I dont beleive you actually need to do that for test data, since the dynamic RNN will unroll as needed.

https://github.com/mkowoods/dlnd/blob/master/34_sentiment_rnn/Using%20Sentiment%20model%20as%20a%20predictor.ipynb

**Comment by mcleonard** [comment]
@TheRusskiy I haven't had a chance to work on this yet. I might have some spare time next week.
